version: '3'
services:
  rabbitmq:
    hostname: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5671:5671

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  product:
      image: "arieloliver/ms-product:v1"
      ports:
        - "8081:8081"

  catalog:
    image: "arieloliver/ms-catalog:v1"
    environment:
      PRODUCT_URL: "http://product:8081"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  checkout:
    image: "arieloliver/ms-checkout:v1"
    environment:
      PRODUCT_URL: "http://product:8081"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_HOST: "rabbitmq"
      RABBITMQ_DEFAULT_PORT: "5672"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  order-checkout:
    image: "arieloliver/ms-order:v1"
    environment:
      PRODUCT_URL: "http://product:8081"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_HOST: "rabbitmq"
      RABBITMQ_DEFAULT_PORT: "5672"
      RABBITMQ_DEFAULT_VHOST: "/"
      REDIS_HOST: "redis"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  order-payment:
    image: "arieloliver/ms-order:v1"
    environment:
      PRODUCT_URL: "http://product:8081"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_HOST: "rabbitmq"
      RABBITMQ_DEFAULT_PORT: "5672"
      RABBITMQ_DEFAULT_VHOST: "/"
      REDIS_HOST: "redis"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    command: ["order", "-opt", "payment"]

  payment:  
    image: "arieloliver/ms-payment:v1"
    environment:
      PRODUCT_URL: "http://product:8081"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_HOST: "rabbitmq"
      RABBITMQ_DEFAULT_PORT: "5672"
      RABBITMQ_DEFAULT_VHOST: "/"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
